-- =============================================================================
-- Migración 03 — Etapa 1: verificación de email + auth provider
-- =============================================================================
-- 1) usuario: agrega `verificado` y `auth_provider`.
--    Estrategia segura: ADD NULL -> backfill -> SET NOT NULL.
--    DECISIÓN DEL EQUIPO: los usuarios EXISTENTES quedan verificado=false
--    (deben verificar su email). Para desbloquear cuentas cuyo email no es real
--    (p.ej. el admin de dev) usar el helper de abajo manualmente.
-- 2) crea la tabla codigo_verificacion.
-- Idempotente. No depende de ddl-auto.
-- =============================================================================

-- ── usuario.verificado / auth_provider ──────────────────────────────────────
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS verificado    boolean;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS auth_provider varchar(20);

-- Backfill: existentes NO verificados (decisión del equipo), provider LOCAL
UPDATE usuario SET verificado    = false   WHERE verificado    IS NULL;
UPDATE usuario SET auth_provider = 'LOCAL' WHERE auth_provider IS NULL;

-- Verificación (no debe haber NULLs):
-- SELECT id, email, verificado, auth_provider FROM usuario ORDER BY id;

ALTER TABLE usuario ALTER COLUMN verificado    SET NOT NULL;
ALTER TABLE usuario ALTER COLUMN auth_provider SET NOT NULL;
ALTER TABLE usuario ALTER COLUMN verificado    SET DEFAULT false;
ALTER TABLE usuario ALTER COLUMN auth_provider SET DEFAULT 'LOCAL';

-- ── tabla codigo_verificacion ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS codigo_verificacion (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  bigint       NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    codigo      varchar(6)   NOT NULL,
    expira_en   timestamp    NOT NULL,
    intentos    integer      NOT NULL DEFAULT 0,
    consumido   boolean      NOT NULL DEFAULT false,
    created_at  timestamp    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_codigo_verif_usuario ON codigo_verificacion(usuario_id);

-- ── Helper de desarrollo (NO se ejecuta por defecto) ────────────────────────
-- Desbloquear manualmente una cuenta cuyo email no es real:
-- UPDATE usuario SET verificado = true WHERE email = 'guadadiosa@mail.com';
