-- =============================================================================
-- Migración 07 — Etapa 4: tabla pago
-- =============================================================================
-- Operación de pago por reserva. NO guarda datos sensibles de tarjeta:
-- solo el id de preferencia/transacción del proveedor (Mercado Pago) y el estado.
-- `reserva.estado` ahora puede valer 'PENDIENTE_PAGO' (enum guardado como varchar,
-- no requiere cambio de esquema).
-- Idempotente. Reversible.
-- =============================================================================

CREATE TABLE IF NOT EXISTS pago (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id     bigint        NOT NULL UNIQUE REFERENCES reserva(id) ON DELETE CASCADE,
    monto          double precision NOT NULL,
    metodo         varchar(20)   NOT NULL,
    estado         varchar(20)   NOT NULL DEFAULT 'PENDIENTE',
    preferencia_id varchar(255),
    proveedor_id   varchar(255),
    created_at     timestamp     NOT NULL DEFAULT now(),
    updated_at     timestamp     NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pago_reserva       ON pago(reserva_id);
CREATE INDEX IF NOT EXISTS idx_pago_preferencia   ON pago(preferencia_id);
CREATE INDEX IF NOT EXISTS idx_pago_proveedor     ON pago(proveedor_id);

-- El check de reserva.estado lo creó Hibernate con los valores viejos y no se
-- actualiza solo al sumar PENDIENTE_PAGO. Se recrea incluyendo el nuevo estado.
ALTER TABLE reserva DROP CONSTRAINT IF EXISTS reserva_estado_check;
ALTER TABLE reserva ADD CONSTRAINT reserva_estado_check
    CHECK (estado IN ('PENDIENTE_PAGO','ACTIVA','CANCELADA','RECHAZADA'));
